// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Mobile.Automation.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Register Validation")]
    public partial class RegisterValidationFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "RegisterValidation.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Register Validation", "\tAs a user\r\n\tI want to see validation errors\r\n\tSo that I can correct my mistake", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("I am on the onboarding screen", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
  testRunner.And("I navigate to register", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("No Details Entered")]
        public virtual void NoDetailsEntered()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No Details Entered", ((string[])(null)));
#line 10
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 11
 testRunner.When("I register", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
 testRunner.Then("I should see the register error \"Whoops! Please enter a valid email address.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Register Validation")]
        [NUnit.Framework.TestCaseAttribute("", "password123", "John", "Smith", "Male", "Default", "WD17 1JJ", "Whoops! Please enter a valid email address.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "", "John", "Smith", "Male", "Default", "WD17 1JJ", "Please enter a password.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "password123", "", "Smith", "Male", "Default", "WD17 1JJ", "Please enter your first name.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "password123", "John", "", "Male", "Default", "WD17 1JJ", "Please enter your last name.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "password123", "John", "Smith", "", "Default", "WD17 1JJ", "Please select your gender.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "password123", "John", "Smith", "Male", "EMPTY", "WD17 1JJ", "Please select your date of birth.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "password123", "John", "Smith", "Male", "Default", "", "Please enter your postcode.", new string[0])]
        [NUnit.Framework.TestCaseAttribute("ami.patel@testukv.co.uk", "password123", "John", "Smith", "Male", "Default", "ABCD EFG", "Please enter a valid postcode.", new string[0])]
        public virtual void RegisterValidation(string email, string password, string firstName, string lastName, string gender, string dOB, string postCode, string error, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register Validation", exampleTags);
#line 14
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Email",
                        "Password",
                        "FirstName",
                        "LastName",
                        "Gender",
                        "DOB",
                        "PostCode"});
            table1.AddRow(new string[] {
                        string.Format("{0}", email),
                        string.Format("{0}", password),
                        string.Format("{0}", firstName),
                        string.Format("{0}", lastName),
                        string.Format("{0}", gender),
                        string.Format("{0}", dOB),
                        string.Format("{0}", postCode)});
#line 15
 testRunner.When("I register an invalid user with the following details", ((string)(null)), table1, "When ");
#line 18
 testRunner.Then(string.Format("I should see the register error \"{0}\"", error), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
